apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: 332352763544.dkr.ecr.ap-south-1.amazonaws.com/my-node-app:latest
          ports:
            - containerPort: 3000
